DBNAME = 'polify_db'

WAITING_ROOM = 'waiting_room'
BATTLES = 'battles'
USERS = 'users'
QUESTIONS = 'questions'

SCORE_WAIT_INTERVAL = 30

COINS_POOL_ONE_VS_ONE = 50
COINS_POOL_MULTIPLAYER = 25

STATUS_OFFLINE = 0
STATUS_ONLINE = 1
STATUS_BUSY = 2
STATUS_WAITING = 3

BATTLE_ONE_VS_ONE = '1v1'
BATTLE_MULTIPLAYER = 'Private room'
